default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgres
  pool: 5
  port: 5432

development:
  <<: *default
  database: fam_dev

test:
  <<: *default
  database: fam_test

production:
  <<: *default
  database: fam_prod
